# Build settings

port: 4000
markdown:  kramdown
permalink: /:title
plugins:   [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		   "Yun's Foot Prints"
description: "Powered by Jekyll and yoonk1228's GitHub Pages"
author:      "yunjaeKim"
